//
// Created by Daniel Lipszyc on 4/20/25.
//

#ifndef PROJECT3_HEARTATTACKPREDICTION_PATIENTOBJECT_H
#define PROJECT3_HEARTATTACKPREDICTION_PATIENTOBJECT_H


class PatientObject {

};


#endif //PROJECT3_HEARTATTACKPREDICTION_PATIENTOBJECT_H
